export const BASE_URL = "http://localhost:8080/"
export const STUDENT_URL = "http://localhost:8080/api/v1/student"
export const COURSE_URL = "http://localhost:8080/api/v1/courses"
export const LOGIN_URL = "http://localhost:8080/api/v1/student/login/auth"
export const REGISTER_URL = "http://localhost:8080/api/v1/student/registration/auth"
export const LOGOUT_URL = "http://localhost:8080/api/v1/student/auth/logout"
